[package]
name = "rxrs"
version = "0.2.0-beta1"
description="Reactive Extensions for Rust"
license="MIT"
repository="https://github.com/yingDev/rxrs"
authors = ["yingDev <me@yingDev.com>"]
edition = "2018"

[dependencies]
